/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evoting;

/**
 *
 * @author DZAKY
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Cek apa pilihan default di ComboBox saat aplikasi pertama jalan
        String defaultRole = cmbRole.getSelectedItem().toString();
        if (defaultRole.equals("Admin")) {
            lblKeterangan1.setText("Username");
            lblKeterangan2.setText("Password");
        } else {
            lblKeterangan1.setText("NIM / NIK");
            lblKeterangan2.setText("Token");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKeterangan1 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lblKeterangan2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblKeterangan1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblKeterangan1.setText("Nama");
        lblKeterangan1.setPreferredSize(new java.awt.Dimension(100, 28));

        cmbRole.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pemilih" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N

        btnLogin.setBackground(new java.awt.Color(0, 204, 255));
        btnLogin.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        jLabel2.setText("E-VOTING LOGIN ");

        lblKeterangan2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblKeterangan2.setText("Password");
        lblKeterangan2.setPreferredSize(new java.awt.Dimension(100, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblKeterangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(371, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(361, 361, 361)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeterangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnLogin)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel2)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari form
            String role = cmbRole.getSelectedItem().toString(); // Mendapatkan pilihan "Admin" atau "Pemilih"
            String usernameOrNim = txtUser.getText();
            String passwordOrToken = new String(txtPass.getPassword()); // Mengambil teks dari JPasswordField

            // 2. Validasi form kosong
            if(usernameOrNim.isEmpty() || passwordOrToken.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Mohon isi semua kolom login!");
                return;
            }

            java.sql.Connection conn = Config.configDB(); // Memanggil koneksi database Anda

            // 3. Percabangan Logika berdasarkan Role
            if (role.equals("Admin")) {
                // --- JIKA YANG LOGIN ADMIN ---
                String sql = "SELECT * FROM tb_admin WHERE username=? AND password=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, usernameOrNim);
                pst.setString(2, passwordOrToken);
                java.sql.ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Login Admin Berhasil!");
                    new Admin().setVisible(true); // Membuka halaman Admin
                    this.dispose(); // Menutup form login
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password Admin salah!");
                }

            } else if (role.equals("Pemilih")) {
                // --- PENGECEKAN SESI BARU DARI DATABASE ---
                String statusSesiDB = "Tutup"; // Nilai default keselamatan
                try {
                    String sqlSesi = "SELECT status_sesi FROM tb_setting WHERE id = 1";
                    java.sql.Statement stmSesi = conn.createStatement();
                    java.sql.ResultSet rsSesi = stmSesi.executeQuery(sqlSesi);
                    if (rsSesi.next()) {
                        statusSesiDB = rsSesi.getString("status_sesi");
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal memeriksa status sesi: " + e.getMessage());
                    return;
                }

                if (statusSesiDB.equals("Tutup")) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Maaf, Sesi Pemilihan belum dibuka atau sudah ditutup oleh Panitia!", "Akses Ditolak", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return; // Menghentikan proses login
                }

                // --- JIKA YANG LOGIN PEMILIH ---
                String sql = "SELECT * FROM tb_pemilih WHERE nim=? AND token=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, usernameOrNim);
                pst.setString(2, passwordOrToken);
                java.sql.ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    // Cek status vote, JANGAN izinkan login jika sudah memilih!
                    String status = rs.getString("status_vote");

                    if(status.equals("Sudah")){
                        javax.swing.JOptionPane.showMessageDialog(this, "Maaf, Anda sudah menggunakan hak suara!", "Akses Ditolak", javax.swing.JOptionPane.ERROR_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil! Silakan gunakan hak suara Anda.");

                        // MENGHUBUNGKAN KE FORM PEMILIH (Mengirimkan NIM)
                        new FormPemilih(usernameOrNim).setVisible(true);

                        this.dispose(); // Menutup form login
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "NIM atau Token Pemilih salah!");
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Koneksi Database Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
        // Mengambil nilai yang sedang dipilih di ComboBox
        String role = cmbRole.getSelectedItem().toString();

        // Mengubah teks label berdasarkan pilihan
        if (role.equals("Admin")) {
            lblKeterangan1.setText("Username");
            lblKeterangan2.setText("Password");
        } else if (role.equals("Pemilih")) {
            lblKeterangan1.setText("NIM");
            lblKeterangan2.setText("Token");
        }
    }//GEN-LAST:event_cmbRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKeterangan1;
    private javax.swing.JLabel lblKeterangan2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
